// app/layout.js
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./Providers";
import ClientLayout from "./clientLayout";
import { ToastContainer } from "react-toastify";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <ToastContainer position="top-right" />

        <NextAuthProvider>
          <ClientLayout>{children}</ClientLayout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
