import { Roboto } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./Providers";
import { DM_Sans, Poppins } from "next/font/google";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
